require('dotenv').config()

export const env = {
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  APP_HOST: process.env.APP_HOST,
  APP_PORT: process.env.APP_PORT,
  BUILD_MODE: process.env.BUILD_MODE,
  SENDINBLUE_API_KEY: process.env.SENDINBLUE_API_KEY,

  ACCESS_TOKEN_SECRET_SIGNATURE : process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_SECRET_LIFE : process.env.ACCESS_TOKEN_SECRET_LIFE,

  REFRESH_TOKEN_SECRET_SIGNATURE : process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_SECRET_LIFE : process.env.REFRESH_TOKEN_SECRET_LIFE,

  OTP_TOKEN_SECRET_SIGNATURE : process.env.OTP_TOKEN_SECRET_SIGNATURE,
  OTP_TOKEN_SECRET_LIFE : process.env.OTP_TOKEN_SECRET_LIFE,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  REDIS_USERNAME: process.env.REDIS_USERNAME,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  SLACK_HOST: process.env.SLACK_HOST,

  MAP_API_KEY: process.env.MAP_API_KEY,

  PLACE_TEXT_SEARCH_BASE_URL: process.env.PLACE_TEXT_SEARCH_BASE_URL,
  PLACE_DETAILS_BASE_URL: process.env.PLACE_DETAILS_BASE_URL,
  PLACE_PHOTOS_BASE_URL: process.env.PLACE_PHOTOS_BASE_URL,

  LANGUAGE_CODE_DEFAULT: process.env.LANGUAGE_CODE_DEFAULT,
  RADIUS_DEFAULT: process.env.RADIUS_DEFAULT,
  WIDTH_PHOTO_DEFAULT: process.env.WIDTH_PHOTO_DEFAULT
}
